### ISSUE TITLE
Dr. Greger (NutritionFacts.org) Daily Dozen |> Meal Plan!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/health#116]
I like Dr. Greger’s Daily Dozen because he has done _considerable_ medical/scientific research into it.
https://nutritionfacts.org/video/dr-gregers-daily-dozen-checklist-2/

https://nutritionfacts.org/app/uploads/2018/03/metric.png
![image](https://user-images.githubusercontent.com/194400/66463521-1ff90f00-ea75-11e9-9187-e358d0c9c046.png)

This `.png` prints out well on A4 and has good content but also has a lot of noise and isn't really a _system_. What we need is a Daily Meal Plan that _automatically_ includes _all_ of the items.
That way way people don't have to _think_ about what to eat/drink and can just get on with their lives.
Then we can compile the Daily Meal Plan into a _Weekly_ grocery shopping list and _hey presto_ we solve the obesity and chronic (_diet-relate_) illness "crisis". 

# Todo: Create a _Daily Meal Plan_

+ [ ] **Wake Up**: **Drink 1 Litre** of **Cold Brew Green Tea** (_prepared the night before put in fridge_)
  alternatively if you prefer hot/warm tea go with that. If tea is unavailable or you don't _like_ tea, fruit-flavoured water (_that you make yourself by adding a few berries or your favourite fruit to water and leaving it in the fridge overnight_) is always an option. Lemon water is great because it's alkalising. 
+ [ ] "Breakfast" or "snack": (_which I usually have after midday when 23:1 fasting_)
  + [ ] Overnight Oats (whole grain) with the following additions soaked overnight in the glass container:
    + [ ] 60g mixed (frozen or fresh) berries
    + [ ] 30g Almonds (_or mixed nuts_)
    + [ ] 1 Tablespoon of Flaxseed
    + [ ] 1 Teaspoon of Chia Seeds
    + [ ] 1 Teaspoon of Cinnamon 
+ [ ] "Lunch" (_my main meal of the day_) usually a Salad featuring the following ingredients:
  + [ ] Lettuce (_shredded. whichever kind is available, usually iceberg_)
  + [ ] Spinach (_just washed_)
  + [ ] Broccoli (_washed and lightly steamed to conserve nutrients but improve flavour_)
  + [ ] Tomato (small cubes)
  + [ ] Cucumber (_quarter slices_)
  + [ ] Grated Carrots (_peeled and grated_)
  + [ ] Sweetcorn (_one small can, drained_)
  + [ ] Apple (_one or two apples chopped small_)
  + [ ] Avocado (_optional. depending on availability or preference_)
  + [ ] Oregano (_dried_)
  + [ ] Canned Fish: Sardines in Tomato Sauce (_definitely not for everyone, I like it_)
+ [ ] Raw Green Soup: an easy way to cram in a wide variety of nutrients in a single serving.
  + [ ] Spinach (_**preferably frozen** as it's **much cheaper** but fresh is fine_)
  + [ ] Lettuce (_whatever is available_)
  + [ ] Kale
  + [ ] Cucumber
  + [ ] Celery
  + [ ] Cabbage (_lightly steamed or raw_)
  + [ ] Raw Garlic (_1 clove_)
  + [ ] Tomato
  + [ ] Butter Beans | Chickpeas | Black-eyed Peas (Beans) - canned or bottled
  + [ ] Filtered water 
  + [ ] 1 Teaspoon of Tumeric
  + [ ] 1 Teaspoon of Oregano 
  + [ ] 1 Tablespoon Raw Organic Vinegar
+ [ ] "Dinner" (_if I am feeling hungry in the evening_) -> Cooked Soup
  + [ ] Onion
  + [ ] Garlic
  + [ ] Carrots
  + [ ] Sweet Potato
  + [ ] Cabbage
  + [ ] Tomato
  + [ ] Black Beans

# Exercise

Dr. Greger recommends 40 mins of vigorous exercise per day.
My Apple Watch is configured to require me to do 30 mins.

I exercise _every_ day without fail and have my "streak" 
![image](https://user-images.githubusercontent.com/194400/66550282-f9061000-eb3c-11e9-8cfa-4319c048a47c.png)

Some days I only do the _minimum_ exercise (30 mins) because I'm feeling "lazy":
![image](https://user-images.githubusercontent.com/194400/66550378-2bb00880-eb3d-11e9-8183-162b52d00116.png)

Occasionally I do a _long_ day where I do a _lot_ of standing desk 
and each time I have a pomodor break I use my skipping rope and do HIIT exercise.
(_exercise minutes add up fast if you do 20+ pomodors per day_):
![image](https://user-images.githubusercontent.com/194400/66550553-9103f980-eb3d-11e9-82ef-a9b83f32bacb.png)

I think I have exercise under control. 😉 
I just need to be laser focussed on my sleep and nutrition. 💭

**Comment by nelsonic** [comment]
This is the one I have printed on and stuck on the wall (_yes the walls are wood panel in [Gerês](https://github.com/dwyl/summer)_):
https://www.cityofwaupaca.org/wp-content/uploads/2016/05/Dr-Gregers-Daily-Dozen_DrKay.pdf
[Dr-Gregers-Daily-Dozen.pdf](https://github.com/dwyl/health/files/3711600/Dr-Gregers-Daily-Dozen.pdf)

![image](https://user-images.githubusercontent.com/194400/66557622-1e4d4b00-eb4a-11e9-9bfd-7197502e9026.png)

**Comment by nelsonic** [comment]
Gotta re-print this and put it on the fridge as a reminder.
