### ISSUE TITLE
Peanut Butter, Oat & Fruit Breakfast Bars (Vegan + No Refined Sugar)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/health#141]
Recently tried a Deliciously Ella Peanut Butter Oat Bar ... 
https://deliciouslyella.com/product/peanut-butter-baked-oat-bars/

![image](https://user-images.githubusercontent.com/194400/125696750-326a68c5-fd08-44be-a50f-794e22ea9236.png)

It tasted a little _too_ sweet. And there's a _good_ reason for it: it's **20% refined sugar**!
Obviously, they use **3 types** of **syrup/sugar**: brown rice syrup, coconut sugar and date syrup 
so that it doesn't _look_ like a lot at first glance. 

But it's immediately obvious when you scroll down to the **nutritional information**:

![image](https://user-images.githubusercontent.com/194400/125696809-f521acfd-a22a-4ed1-b53e-05478f2ee367.png)

Also, **`86p`** per **50g** bar (17.5/kg) isn't exactly cheap considering the ingredients are cheap. 
The bar is "gluten free" and "vegan" but does not say it uses _organic_ ingredients; so it _definitely_ doesn't!
The kicker for me is packaging of the bars is **single-use plastic-coated** so cannot be recycled cost-effectively.  🔴

Sample of ingredients at _consumer_ (non-bulk) prices:

https://www.buywholefoodsonline.co.uk/smooth-peanut-butter-100-nuts-1kg.html
![image](https://user-images.githubusercontent.com/194400/125698191-92f30243-21a5-4325-b46e-8cb2039e651e.png)

https://www.buywholefoodsonline.co.uk/organic-jumbo-oats-gluten-free-2-5kg.html
![image](https://user-images.githubusercontent.com/194400/125698264-315d89b5-b982-4c25-a692-1fbd45bd6874.png)

https://www.buywholefoodsonline.co.uk/organic-extra-virgin-raw-coconut-oil-500ml.html
![image](https://user-images.githubusercontent.com/194400/125700320-8c270187-0c5d-4a3a-b554-4bebf1ea844c.png)

There's a **_huge_ margin** in these for _Ella_ ... 💰 (_and they are packaged in single-use plastic...!!_)

# `make` our own bars!

This recipe uses _zero_ refined sugar: https://joyfoodsunshine.com/lauras-peanut-butter-breakfast-bars/#recipe
 (_though honey/maple syrup can be considered refined if we're being picky..._)

![image](https://user-images.githubusercontent.com/194400/125699076-598ac672-a813-48f5-a1db-33adfe245e86.png)

## Recipe:

+ [ ] 1 ½ cup quick cooking oats can use old fashioned but they will be chewier
+ [ ] ½ cup almond meal
+ [ ] ½ cup flaxseed meal 
+ [ ] 2 tsp ground cinnamon
+ [ ] ½ tsp sea salt
+ [ ] 2-4 TBS plant-based vanilla protein powder _optional_
+ [ ] 1 tsp pure vanilla extract
+ [ ] 2 bananas ripe and mashed
+ [ ] ½ cup applesauce
+ [ ] ¼ cup creamy **peanut butter**
+ [ ] 2 TBS honey or **maple syrup** for vegan option
+ [ ] **_More_ peanut butter** for the top about ¼ cup

## Instructions

1. Preheat oven to 350 degrees F. Grease an 8x8 square baking dish
2. In a small bowl combine the dry ingredients (oats, almond meal, flaxseed, salt, cinnamon and protein powder if using), set aside. (alternately add the dry ingredients after mixing the wet ingredients). 
3. In a large bowl mash the banana. Add applesauce, honey, ¼ cup peanut butter and vanilla. Mix well.
4. Stir dry ingredients into wet until combined. Spread mixture into the pan (should be moist but NOT soupy).
5. Bake 20 minutes (should be slightly brown around the edges and top should be set), remove from oven and spread peanut butter over the top of the bars (I like a really thick layer of peanut butter but it’s to your own preference)
6. Continue baking for 10 minutes more or until firm and lightly browned around the edges. At this point the peanut butter layer will have tiny little bubbles in it.
7. Cool completely in the refrigerator and cut into 6 or 9 bars. Wrap each with plastic wrap and store in an airtight container in the fridge for a quick grab and go breakfast!

## Todo

+ [ ] Check if we have vanilla extract and the other dry ingredients
+ [ ] Buy required ingredients from our local organic (no packaging) supermarket.
  + [ ] 4 apples (_freeze the extra sauce_)
  + [ ] 2 large bananas
+ [ ] Convert the recipe to grams and `make` it!
+ [ ] _Taste_ them!
+ [ ] Test replacing the banana with extra apple sauce ... 💭 

@iteles do we have a decent rectangular/square baking tin?

If not, I'm thinking of getting one of these: https://www.ikea.com/gb/en/p/koncis-roasting-tin-stainless-steel-50055863/
![image](https://user-images.githubusercontent.com/194400/125700229-135ad66e-cf52-4e81-a377-8cecce31e4f7.png)

Or if we still have wedding gift money ... https://cookinglife.eu/le-creuset-rectangular-cake-tin-patiliss-33-cm/
![image](https://user-images.githubusercontent.com/194400/125701276-13e27e19-b6a1-4c3a-95b4-5999af143f12.png)

Could always try the muffin tin even if it means the "bars" end up being circular instead of square. 🟫

**Comment by iteles** [comment]
Of course I tried making my own before I bought more bars. 

I can't for the life of me find the recipe but the one I tried was a 4 ingredient one: oats, peanut butter, mashed ripe bananas and a couple of tbsps of maple syrup. 

I found them waaaaay too soggy with a very 'one note' flavor that made them not very moreish. 

Two things I need to change for next time:
- Adding extra peanuts to the mix - I used smooth peanut butter because that was the only 100% peanut butter we had at the time but I really missed the crunch of actual peanut halves in there
- Add salt for a more interesting flavor profile

**Comment by nelsonic** [comment]
@iteles good feedback regarding the 4-ingredient bar. 💭 
If you ever find the recipe, please share. Would be good to know the ratios you used. 👍 
I suspect the salt, vanilla and apple sauce of the OP recipe probably make a difference. 😋 
Extra peanuts or crunchy peanut butter for sure. 🥜
