### ISSUE TITLE
NHS API(s)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/health#68]
https://developer.nhs.uk/apis/
![image](https://cloud.githubusercontent.com/assets/194400/25841796/6f526900-3499-11e7-8bd1-9697d804090e.png)

## Todo:
+ [ ] Make time to read API docs
+ [ ] Pick a simple API out of the _many_
+ [ ] Build MVP/Showcase App that uses the API
